apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-misid
  labels:
    app: devops-misid
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-misid
  template:
    metadata:
      labels:
        app: devops-misid
    spec:
      containers:
      - name: devops-misid
        image: devops-misid:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
